name: neural-oit-env
channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.9
  - pip
  - numpy
  - tqdm
  - click
  - torchvision
  - cpuonly  # if need GPU cudatoolkit=11.3
  - pip:
      - onnx
      - onnxruntime
      - matplotlib  